version: 2
jobs:
  build:
    docker:
      - image: circleci/openjdk:8-jdk-browsers
    steps:
      - checkout

      - run:
          name: Install packages
          command: sudo apt-get update && sudo apt-get install wget zip unzip -y
      - run:
          name: Install pip
          command: sudo apt-get install python-pip -y
      - run:
          name: Install awscli
          command: sudo pip install awscli

      - run:
          name: Scripts
          command: |
            cd CloudWebApp
            pwd
            ls -al
            mvn clean package -DskipTests=true
            cd target/
            ls -al
            cd ../
            pwd
            ls -al
      - run:
          name: Zip Artifact
          command: |
            pwd
            mkdir codedeploy_artifact
            cp infrastructure/aws/codedeploy/*.yml .
            cp infrastructure/aws/codedeploy/*.sh .
            zip -r csye6225-web-app-${CIRCLE_BUILD_NUM}.zip CloudWebApp/target/csye6225-0.0.1-SNAPSHOT.jar *.yml *.sh
            ls -al
            mv csye6225-web-app-${CIRCLE_BUILD_NUM}.zip codedeploy_artifact/
            ls -al
            pwd
            cd ..
            pwd
            ls -al

      - run:
          name: deploy to s3
          command: |
            aws configure list
            aws s3 sync codedeploy_artifact s3://code-deploy.csye6225-spring2019-${BUCKETNAME}.me --region us-east-1

      - run:
          name: deploy to ec2
          command: |
            aws deploy create-deployment --application-name csye6225-webapp --deployment-config-name CodeDeployDefault.AllAtOnce --region us-east-1 --deployment-group-name csye6225-webapp-deployment --description "csye6225 create" --s3-location bucket=code-deploy.csye6225-spring2019-${BUCKETNAME}.me,bundleType=zip,key=csye6225-web-app-${CIRCLE_BUILD_NUM}.zip
